# Generated by Django 4.2.6 on 2023-11-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_img', models.ImageField(upload_to='images/')),
                ('icon_img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
