# Generated by Django 4.2.7 on 2023-12-07 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=300)),
                ('filled_quota', models.PositiveIntegerField(default=0)),
                ('website_quota_limit', models.PositiveIntegerField()),
                ('error_status', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_img', models.ImageField(upload_to='images/')),
                ('icon_img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Website_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=250)),
                ('website_url', models.URLField()),
                ('username', models.CharField(blank=True, max_length=250, null=True)),
                ('application_password', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Youtube_api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('API_Key', models.CharField(max_length=500)),
                ('error_status', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
