# Generated by Django 4.2.7 on 2023-11-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0002_apilist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apilist',
            old_name='api_running_number',
            new_name='api_worker',
        ),
        migrations.AddField(
            model_name='apilist',
            name='api_worker_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
