# Generated by Django 4.2.7 on 2023-12-15 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apilist',
            old_name='website_quota_limit',
            new_name='request_quota_limit',
        ),
    ]
