# Generated by Django 4.2.7 on 2023-11-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0003_rename_api_running_number_apilist_api_worker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apilist',
            name='api_worker',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
