# Generated by Django 4.2.7 on 2023-11-16 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0004_alter_apilist_api_worker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apilist',
            old_name='api_worker',
            new_name='api_working_for',
        ),
        migrations.RenameField(
            model_name='apilist',
            old_name='api_worker_limit',
            new_name='website_limit',
        ),
    ]
