# Generated by Django 4.2.7 on 2023-11-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0005_rename_api_worker_apilist_api_working_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apilist',
            name='website_limit',
            field=models.IntegerField(),
        ),
    ]
