# Generated by Django 4.2.7 on 2023-11-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0007_rename_api_working_for_apilist_filled_quota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apilist',
            name='website_quota_limit',
            field=models.PositiveIntegerField(),
        ),
    ]
