# Generated by Django 4.2.7 on 2023-11-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0008_alter_apilist_website_quota_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.TextField()),
                ('website_url', models.URLField()),
                ('application_password', models.TextField()),
                ('category_name', models.TextField()),
            ],
        ),
    ]
