# Generated by Django 4.2.7 on 2023-11-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0010_alter_website_list_application_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Youtube_api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('API_Key', models.CharField(max_length=500)),
            ],
        ),
    ]
