# Generated by Django 4.2.7 on 2023-11-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0011_youtube_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='apilist',
            name='error_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='youtube_api',
            name='error_status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
