# Generated by Django 4.2.7 on 2023-11-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0013_website_list_user_youtube_api_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='website_list',
            name='username',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
