# Generated by Django 4.2.7 on 2023-11-17 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0014_website_list_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website_list',
            name='category_name',
        ),
    ]
