# -*- coding: utf-8 -*-
"""wordpress posting booknmelody.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ym4TIb0CKgasJgBEBXmZ0r4kamjccO0N
"""

import requests

url = 'https://booknmelody.com/wp-json/wp/v2/book'
username = 'KAI'
password = 'eBqt usW3 gla6 f03H v0Gf VMRY'

# Create a session to persist authentication
session = requests.Session()
session.auth = (username, password)

# Define the book data including custom fields
book_data = {
    'title': 'Your Book Title',
    'content': 'Your book content goes here.',
    'meta': {
        '_reviews': 'Review information goes here',
        '_language': 'English',
        '_publisher': 'Publisher information goes here',
        # Add more custom fields as needed
    },
    'status': 'publish',  # Set to 'publish' to make the book publicly visible
}

# Make the POST request to create a new book
response = session.post(url, json=book_data)

# Check the response
if response.status_code == 201:
    print('Book successfully posted!')
else:
    print(f'Error posting book. Status code: {response.status_code}')
    print(response.text)