# Generated by Django 4.2.7 on 2023-12-07 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info_bulk_Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='\nWrite an SEO title on this keyword within 55 characters and the keyword must be directly included in the title.\nkeyword:  <<keyword>>\n')),
                ('outline_prompt', models.TextField(default='\nWrite outline on this topic <<keyword>>\noutline must be H2: format, not underscore, not symbol, not hyphen, not number and no indentation, under each H2 : will have 4 H3 : not need sub heading for H3 :\nand an important command is, outlines not answer\nand another important command is, do not give me "Introduction" and "Conclusion, each heading length must be less than 7 words.\nH1: <<keyword>>\n')),
                ('introduction', models.TextField(default='\nWrite a article introduction on this keyword intro start with technical terms, not like """are you""" and keyword must be include in output do not give me direct solution in intro section, intro last sentence must be interesting to read the full article, keyword: <<keyword>>\nand length approx. 100 words\n')),
                ('h2_title', models.TextField(default='\nWrite an h2 heading on this keyword within 55 characters before starting the main article and the keyword must be directly included in the title.\nkeyword: <<keyword>>\n')),
                ('paragraph_prompt', models.TextField(default='\nMake sure that you dont follow Ai pattern but article should be really simple and it should make sense. it should be as written with an intermediate level writer, make sure to add a bit of humor and add some funny lines. also on keypoints, you can add <em></em>, if necessary: Write article paragraph section from this heading, interesting, and organized way like human writing but not unnecessary words not long length!\nthe article title of this paragraph is : <<keyword>>,\nparagraph heading is : <<heading>>\nEach output sentence will be short, meaningful and easy to read, that can understand elementary school student.\nyou can add bullet points or table in the section, if its suitable, the bullet points and tables must with <ul><li> tags or <table></table> tag and paragraph is with <p></p> tags \n\n<<prompt separator>>\n\nMake sure that you dont follow Ai pattern but article should be really simple and it should make sense. it should be as written with an intermediate level writer, make sure to add a bit of humor and add some funny lines. also on keypoints, you can add <em></em>,  if necessary: Write article paragraph section from this heading, interesting, and organized way like human writing but not unnecessary words not long length!\nthe article title of this paragraph is : <<keyword>>,\nparagraph heading is : <<heading>>\nplease add a html table in the section, if its suitable, tables must with html <table></table> tag and paragraph is with <p></p> tags.\n')),
                ('faq_question', models.TextField(default='\nTopic: <<keyword>>\nWrite 5 related questions on this topic\n1.\n')),
                ('faq_ans', models.TextField(default='\nWrite a short answer to this question within four sentence <<question>>\n')),
                ('summary', models.TextField(default='\nWrite a short briefing before starting the main article after intro,\nKeyword: <<keyword>>\nMust be include keyword in output.\nand length approx. 120 words\n')),
                ('conclusion_para', models.TextField(default='\nkeyword: <<keyword>>\nWrite an web article bottom summary\n and length approx. 60 words\n')),
                ('excerpt', models.TextField(default='\nWrite a short summary,\nKeyword: <<keyword>>,\nMust be include keyword in output\nand length approx. 25 words\n')),
            ],
        ),
        migrations.CreateModel(
            name='info_bulk_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_name', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('error', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Info_Manual_Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generate_title', models.TextField(blank=True, null=True)),
                ('generate_outline', models.TextField(blank=True, null=True)),
                ('generate_paragraph', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
