# Generated by Django 4.2.7 on 2023-12-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoapp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_manual_command',
            name='generate_outline',
            field=models.TextField(default='\nWrite outline on this topic <<keyword>>\noutline must be H2: format, not underscore, not symbol, not hyphen, not number and no indentation, under each H2 : will have 4 H3 : not need sub heading for H3 :\nand an important command is, outlines not answer\nand another important command is, do not give me "Introduction" and "Conclusion, each heading length must be less than 7 words.\nH1: <<keyword>>\n'),
        ),
        migrations.AlterField(
            model_name='info_manual_command',
            name='generate_paragraph',
            field=models.TextField(default='\nMake sure that you dont follow Ai pattern but article should be really simple and it should make sense. it should be as written with an intermediate level writer, make sure to add a bit of humor and add some funny lines. also on keypoints, you can add <em></em>, if necessary: Write article paragraph section from this heading, interesting, and organized way like human writing but not unnecessary words not long length!\nthe article title of this paragraph is : <<keyword>>,\nparagraph heading is : <<heading>>\nEach output sentence will be short, meaningful and easy to read, that can understand elementary school student.\nyou can add bullet points or table in the section, if its suitable, the bullet points and tables must with <ul><li> tags or <table></table> tag and paragraph is with <p></p> tags \n\n<<prompt separator>>\n\nMake sure that you dont follow Ai pattern but article should be really simple and it should make sense. it should be as written with an intermediate level writer, make sure to add a bit of humor and add some funny lines. also on keypoints, you can add <em></em>,  if necessary: Write article paragraph section from this heading, interesting, and organized way like human writing but not unnecessary words not long length!\nthe article title of this paragraph is : <<keyword>>,\nparagraph heading is : <<heading>>\nplease add a html table in the section, if its suitable, tables must with html <table></table> tag and paragraph is with <p></p> tags.\n'),
        ),
        migrations.AlterField(
            model_name='info_manual_command',
            name='generate_title',
            field=models.TextField(default='\nWrite an SEO title on this keyword within 55 characters and the keyword must be directly included in the title.\nkeyword:  <<keyword>>\n'),
        ),
    ]
