# Generated by Django 4.2.7 on 2023-12-21 16:08

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoapp', '0003_alter_info_manual_command_generate_outline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_bulk_model',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='info_bulk_command',
            name='paragraph_prompt',
            field=models.TextField(default="\nWrite a article paragraph section from this heading, interesting, and organized way like human writing but not unnecessary words not long length. Each output sentence will be short, meaningful and easy to read, that can understand elementary school student.\n\nMake sure that you don't follow Ai pattern but paragraph should be really simple, and it should make sense. it should be as written with an intermediate level writer, make sure to add a bit of humor and add some funny lines. also on key points, you can add <em></em>, if necessary: Write article paragraph section from this heading, interesting, and organized way like human writing but not unnecessary words not long length!\nthe article title of this paragraph is : <<keyword>>,\nparagraph heading is : <<heading>>\nprevious output remember:  <<prompt remember>>\nEach output sentence will be short, meaningful and easy to read, that can understand elementary school student.\nyou can add bullet points or table in the section, if its suitable, the bullet points and tables must with <ul><li> tags or <table></table> tag and paragraph is with <p></p> tags \n\n<<prompt separator>>\n\nWrite a article paragraph section from this heading, interesting, and organized way like human writing but not unnecessary words not long length. Each output sentence will be short, meaningful and easy to read, that can understand elementary school student.\n\nMake sure that you don't follow Ai pattern but paragraph should be really simple and it should make sense. it should be as written with an intermediate level writer, make sure to add a bit of humor and add some funny lines. also on key points, you can add <em></em>,  if necessary: Write article paragraph section from this heading, interesting, and organized way like human writing but not unnecessary words not long length!\nthe article title of this paragraph is : <<keyword>>,\nparagraph heading is : <<heading>>\nprevious output remember:  <<prompt remember>>\nplease add a html table in the section, if its suitable, tables must with html <table></table> tag and paragraph is with <p></p> tags.\n"),
        ),
        migrations.AlterField(
            model_name='info_manual_command',
            name='generate_paragraph',
            field=models.TextField(default="\nWrite a article paragraph section from this heading, interesting, and organized way like human writing but not unnecessary words not long length. Each output sentence will be short, meaningful and easy to read, that can understand elementary school student.\n\nMake sure that you don't follow Ai pattern but paragraph should be really simple, and it should make sense. it should be as written with an intermediate level writer, make sure to add a bit of humor and add some funny lines. also on key points, you can add <em></em>, if necessary: Write article paragraph section from this heading, interesting, and organized way like human writing but not unnecessary words not long length!\nthe article title of this paragraph is : <<keyword>>,\nparagraph heading is : <<heading>>\nprevious output remember:  <<prompt remember>>\nEach output sentence will be short, meaningful and easy to read, that can understand elementary school student.\nyou can add bullet points or table in the section, if its suitable, the bullet points and tables must with <ul><li> tags or <table></table> tag and paragraph is with <p></p> tags \n\n<<prompt separator>>\n\nWrite a article paragraph section from this heading, interesting, and organized way like human writing but not unnecessary words not long length. Each output sentence will be short, meaningful and easy to read, that can understand elementary school student.\n\nMake sure that you don't follow Ai pattern but paragraph should be really simple and it should make sense. it should be as written with an intermediate level writer, make sure to add a bit of humor and add some funny lines. also on key points, you can add <em></em>,  if necessary: Write article paragraph section from this heading, interesting, and organized way like human writing but not unnecessary words not long length!\nthe article title of this paragraph is : <<keyword>>,\nparagraph heading is : <<heading>>\nprevious output remember:  <<prompt remember>>\nplease add a html table in the section, if its suitable, tables must with html <table></table> tag and paragraph is with <p></p> tags.\n"),
        ),
    ]
