# Generated by Django 5.0 on 2023-12-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_creditpackage_appuser_credit_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='expire_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='creditpackage',
            name='days',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='creditpackage',
            name='credits',
            field=models.IntegerField(default=0),
        ),
    ]
