# Generated by Django 5.0 on 2023-12-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_appuser_expire_date_creditpackage_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='expire_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
