# Generated by Django 5.0 on 2023-12-26 14:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_alter_appuser_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='expire_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
